import React from "react";
import "react-table-6/react-table.css";
import classes from "./Formd.module.css";
//import App from './App';
//import * as React from 'react';

const Formd = () => {
  return (
    <>
      <h1>Form table</h1>
      <table>
        <tr>
          <br></br>
          <h5 className={classes.sp}>QUESTIONS</h5>
          <td> 1</td>
          <br></br>
          <td> 2</td>
          <br></br>
          <td> 3</td>
          <br></br>
          <td> 4</td>
          <br></br>
          <td> 5</td>
          <br></br>
          <td> 6</td>
          <br></br>
          <td> 7</td>
          <br></br>
          <td> 8</td>
          <br></br>
          <td> 9</td>
          <br></br>
          <td> 10</td>
          <br></br>
        </tr>

        <tr>
          <br></br>
          <h5>Job Satisfaction</h5>

          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age1"
              name="age"
              value="1"
            />
          </td>
          <br></br>

          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age1"
              name="age"
              value="1"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age1"
              name="age"
              value="1"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age1"
              name="age"
              value="1"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age1"
              name="age"
              value="1"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age1"
              name="age"
              value="1"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age1"
              name="age"
              value="1"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age1"
              name="age"
              value="1"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age1"
              name="age"
              value="1"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age1"
              name="age"
              value="1"
            />
          </td>
          <br></br>
        </tr>
        <tr>
          <h5>How hepful was the job suggestion?</h5>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age2"
              name="age2"
              value="30"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age2"
              name="age2"
              value="30"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age2"
              name="age2"
              value="30"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age2"
              name="age2"
              value="30"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age2"
              name="age2"
              value="30"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age2"
              name="age2"
              value="30"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age2"
              name="age2"
              value="30"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age2"
              name="age2"
              value="30"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age2"
              name="age2"
              value="30"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age2"
              name="age2"
              value="30"
            />
          </td>
          <br></br>
        </tr>
        <tr>
          <h5>xyz</h5>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age1"
              name="age3"
              value="1"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age1"
              name="age3"
              value="1"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age1"
              name="age3"
              value="1"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age1"
              name="age3"
              value="1"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age1"
              name="age3"
              value="1"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age1"
              name="age3"
              value="1"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age1"
              name="age3"
              value="1"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age1"
              name="age3"
              value="1"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age1"
              name="age3"
              value="1"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age1"
              name="age3"
              value="1"
            />
          </td>
          <br></br>
        </tr>
        <tr>
          <h5>ZYX</h5>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age4"
              name="age4"
              value="30"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age4"
              name="age4"
              value="30"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age4"
              name="age4"
              value="30"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age4"
              name="age4"
              value="30"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age4"
              name="age4"
              value="30"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age4"
              name="age4"
              value="30"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age4"
              name="age4"
              value="30"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age4"
              name="age4"
              value="30"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age4"
              name="age4"
              value="30"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age4"
              name="age4"
              value="30"
            />
          </td>
          <br></br>
        </tr>
        <tr>
          <h5>How much would you like to rate our portal</h5>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age6"
              name="age6"
              value="30"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age4"
              name="age6"
              value="30"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age4"
              name="age6"
              value="30"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age4"
              name="age6"
              value="30"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age4"
              name="age6"
              value="30"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age4"
              name="age6"
              value="30"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age4"
              name="age6"
              value="30"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age4"
              name="age6"
              value="30"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age4"
              name="age6"
              value="30"
            />
          </td>
          <br></br>
          <td>
            <input
              className={classes.th1}
              type="radio"
              id="age4"
              name="age6"
              value="30"
            />
          </td>
          <br></br>
        </tr>
      </table>
      <br></br>
      <div className={classes.cont1}>
        <input type="submit" value="Submit" />
      </div>
    </>
  );
};
export default Formd;
